### ISSUE TITLE
TypeError: '>=' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by Buadhai** [jrmann100/notifwd#2]
I'm running notifwd on a 2017 iMac with Catalina

```
MrMuscle:notifwd mnewman$ ./notifwd.py --api-key [my api-key]

  _   _       _   _ _____             _ 
 | \ | | ___ | |_(_)  ___|_      ____| |
 |  \| |/ _ \| __| | |_  \ \ /\ / / _` |
 | |\  | (_) | |_| |  _|  \ V  V / (_| |
 |_| \_|\___/ \__|_|_|     \_/\_/ \__,_|

notifwd by Jordan Mann. Starting up... done.
Starting scheduler. Update frequency is 60 seconds...Traceback (most recent call last):
  File "./notifwd.py", line 191, in <module>
    Notification.main(argv)
  File "./notifwd.py", line 96, in main
    raise(e)
  File "./notifwd.py", line 90, in main
    s.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "./notifwd.py", line 82, in scheduled_update
    Notification.check()
  File "./notifwd.py", line 147, in check
    while sql_data[0] != Notification.last_id and sql_data[6] >= Notification.last_date:
TypeError: '>=' not supported between instances of 'float' and 'NoneType'

```

I don't know anything about Python, so all I can do is let you know about the error.

**Comment by Buadhai** [comment]
I am testing this by using terminal-notifier to create a system notification:

`MrMuscle:~ mnewman$ terminal-notifier -message "this is the messge" -title "this is the title"`

But that results in this:

```
Starting scheduler. Update frequency is 60 seconds...
Sending new notification! There was a notification 0 minutes ago from : —this is the messge (...)
Received unexpected status code 400 Bad Request response:
 <?xml version="1.0" encoding="UTF-8"?>
<prowl>
<error code="400">Missing field: Application is required.</error>
</prowl>

```

**Comment by Buadhai** [comment]
And, one more. It seems to work fine on a 2010 MacBook running High Sierra:

`Whitey:~ mnewman$ terminal-notifier -title "This is the title" -message "Here it is"`

```
notifwd by Jordan Mann. Starting up... done.
Starting scheduler. Update frequency is 60 seconds...
Sending new notification! There was a notification 0 minutes ago from terminal-notifier.app: —Here it is (...)
```

No idea why it works with High Sierra, but not Catalina

**Comment by Buadhai** [comment]
It seems that this code is not working in Catalina:

`Line 164: this.app = Notification.lookup_display_name(value)`

If I stick this in there instead:

`this.app = "dummy.app"`

There error message goes away and the Prowl notice gets sent:

`Sending new notification! There was a notification 0 minutes ago from dummy.app: —this is for you (...)`

**Comment by jrmann100** [comment]
Not all notifications are created equally, and I think I'm missing a large amount of fallback values. I'll try to fill these in.

**Comment by jrmann100** [comment]
It actually looks like I have a fix in my local copy. I'll include it in my next commit.

**Comment by Buadhai** [comment]
Thanks for the reply. 

I still think it’s odd that it works fine in High Sierra but not Catalina. 

Mike

-- 
www.mgnewman.com

**Comment by Buadhai** [comment]
Thanks. I’ll look for it. 

-- 
www.mgnewman.com

**Comment by homepin** [comment]
can someone explain better the steps for a novice user in order to be able to start this script?

**Comment by homepin** [comment]
> can someone explain better the steps for a novice user in order to be able to start this script?

no help needed, i managed to make it work
