### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by jriggz** [jrmann100/notifwd#3]
This is on macOS 10.10; I don't have much experience with sqlite3, but I can help troubleshoot.

```
seedbox:notifwd gia$ ./notifwd.py

  _   _       _   _ _____             _
 | \ | | ___ | |_(_)  ___|_      ____| |
 |  \| |/ _ \| __| | |_  \ \ /\ / / _` |
 | |\  | (_) | |_| |  _|  \ V  V / (_| |
 |_| \_|\___/ \__|_|_|     \_/\_/ \__,_|

notifwd by Jordan Mann. Starting up... Traceback (most recent call last):
  File "/Users/gia/notifwd/./notifwd.py", line 200, in <module>
    Notification.main(argv)
  File "/Users/gia/notifwd/./notifwd.py", line 78, in main
    Notification.setup(argv)
  File "/Users/gia/notifwd/./notifwd.py", line 65, in setup
    Notification.connection = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
```

**Comment by jrmann100** [comment]
What is the result of running `stat $(getconf DARWIN_USER_DIR)/com.apple.NotificationCenter/db2/db`?

**Comment by jriggz** [comment]
```
stat: /var/folders/_m/glqnz_6n24qbpdtg5zn645f00000gn/0//com.apple.NotificationCenter/db2/db: stat: No such file or directory
```

**Comment by jriggz** [comment]
> What is the result of running `stat $(getconf DARWIN_USER_DIR)/com.apple.NotificationCenter/db2/db`?

```
stat: /var/folders/_m/glqnz_6n24qbpdtg5zn645f00000gn/0//com.apple.NotificationCenter/db2/db: stat: No such file or directory
```

**Comment by PTrottier** [comment]
I would encourage you to try the following instead:
``
stat $(getconf DARWIN_USER_DIR)com.apple.notificationcenter/db2/db
``
Changes:
- Notice that `$(getconf DARWIN_USER_DIR)` produces a terminating slash resulting in a double slash 
- Looking into the directory of `$(getconf DARWIN_USER_DIR)` (try `cd $(getconf DARWIN_USER_DIR)`), I noticed that `NotificationCenter` was spelled with lowercases instead `notificationcenter`

I hope this helps as it did for me, this is such a phenomenal tool, thank you for your work!
